export const MessageTypes = [
    'DEFAULT',
    'RECIPIENT_ADD',
    'RECIPIENT_REMOVE',
    'CALL',
    'CHANNEL_NAME_CHANGE',
    'CHANNEL_ICON_CHANGE',
    'CHANNEL_PINNED_MESSAGE',
    'GUILD_MEMBER_JOIN',
    'USER_PREMIUM_GUILD_SUBSCRIPTION',
    'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1',
    'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2',
    'USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3',
    'CHANNEL_FOLLOW_ADD',
    null,
    'GUILD_DISCOVERY_DISQUALIFIED',
    'GUILD_DISCOVERY_REQUALIFIED',
    'GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING',
    'GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING',
    'THREAD_CREATED',
    'REPLY',
    'APPLICATION_COMMAND',
    'THREAD_STARTER_MESSAGE',
    'GUILD_INVITE_REMINDER',
    'CONTEXT_MENU_COMMAND'
];
export const SystemMessageTypes = exports.MessageTypes.filter(
    type => type && !['DEFAULT', 'REPLY', 'APPLICATION_COMMAND', 'CONTEXT_MENU_COMMAND'].includes(type)
);
